### PR TITLE
05 02 emode updates, updated with new recommendations

### PR DESCRIPTION
**Pull request by reem**
Implements RR-120

IPFS Preview: https://app.aave.com/governance/ipfs-preview/?ipfsHash=0x597779e8a7564df81730fbb0522ee52147427851c335df92bc297d332de34dc2

### CODE REVIEW

**Comment by jmomx** [comment]
The IPFS preview seems to be inconsistent: 

image


but then 

image


so no mode params are changing _to_ 97

**Review by jmomx — COMMENTED** [review]
[Optimisim](https://optimistic.etherscan.io/address/0xf22c8255ea615b3da6ca5cf5aecc8956bff07aa8#code) - Looks good (lt and ltv)
[polygon](https://polygonscan.com/address/0x24bdacf6bbebaf567123da16cdb79a266597e92b#code) - Look good (lt and ltv)
[arbitrum](https://arbiscan.io/address/0x142dcaec322aaa25141b2597bf348487adbd596d#code) - Looks good (lt and ltv)
[avalanche](https://snowtrace.io/address/0xfc7b55cc7c5bd3ae89ac679c7250ab30754c5cc5) - also looks good

didnt see any other changes in the payload than the ones described

Happy to approve once we reconcile the summary in the description on ipfs

**Review by jmomx — CHANGES_REQUESTED** [review]
Confirmed with paul. summary is incorrect. how should i best submit a new summary text? what is the process?

**Comment by reem** [comment]
@jmomx @ringwraith10 updated the description, please review again

**Review by WatFu — APPROVED** [review]
LGTM. Forked blocks were from 2 days ago and IPFS preview is correct.

**Review by jmomx — APPROVED** [review]
ipfs looks good

**Comment by WatFu** [comment]
As a side note, I double checked all of the values for emode_category and stablecoin is always 1. For LSTs, they could be different so we should keep that in mind for future proposals on LSTs

**Comment by reem** [comment]
Queued in safe

**Pull request closed without merging**
