### PR TITLE
Add mai update.

### PR DESCRIPTION
**Pull request by reem**
IPFS preview: https://app.aave.com/governance/ipfs-preview/?ipfsHash=0xc74f19fc8bb41498edc38f2da7cbc45e2e6d8adb1d28e50793df07328fb56377

Jira: https://gauntlet-network.atlassian.net/browse/RR-209

### CODE REVIEW

**Review by reichiang — APPROVED** [review]
lgtm

**Review by ringwraith10 — APPROVED** [review]
lgtm

**Review by ringwraith10 — APPROVED** [review]
lgtm

**Comment by reem** [comment]
Queued in multisig

**Pull request closed without merging**
